### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by rtubio** [satnet-project/protocol#7]
When running the installation script, the following errors occur:

1) the config for supervisord points to the directories with routes relative to the user "sgongar", which may not exist;
2) after reboot, supervisord is not running;
3) when using supervisorctl, the following exception occurs:

    unix:///var/run/supervisor.sock no such file

4) during the installation, the following exception occurs:

    mkdir: cannot create directory ‘build’: File exists
    Downloading/unpacking SIP
    Could not find any downloads that satisfy the requirement SIP
    Cleaning up...
    No distributions at all found for SIP
    Storing debug log for failure in /home/rtubiopa/.pip/pip.log
    unzip:  cannot find or open sip*, sip*.zip or sip*.ZIP.
    No zipfiles found.
    antes de uno

5) at the end of the PyQT installation, the following error occurs:

    configure.py: error: '/usr/bin/qmake-qt4' is not a file
    make: *** No targets specified and no makefile found.  Stop.
    make: *** No rule to make target `install'.  Stop.

6) during the configuration of the keys, there are some issues:

    >>> Generating key bundles
    mv: cannot move ‘key’ to ‘../key’: Directory not empty

    >>> This script will generate a daemon for SATNet protocol
    >>> Populating directories
    mkdir: cannot create directory ‘/home/rtubiopa/.satnet/’: File exists
    mkdir: cannot create directory ‘/home/rtubiopa/.satnet/logs/’: File exists
    mkdir: cannot create directory ‘/opt/satnet’: File exists
    cp: cannot stat ‘../../protocol’: No such file or directory
    sudo: shc: command not found
    rm: cannot remove ‘satnetprotocol.sh.x.c’: No such file or directory
    chmod: cannot access ‘satnetprotocol.sh.x’: No such file or directory
    chown: cannot access ‘satnetprotocol.sh.x’: No such file or directory
    mv: cannot stat ‘satnetprotocol.sh.x’: No such file or directory
    mkdir: cannot create directory ‘/home/rtubiopa/bin/’: File exists
    mv: cannot stat ‘satnetprotocol’: No such file or directory
    >>> Copying daemons
    >>> Updating Supervisor
    error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 224
    error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 224
    chown: cannot access ‘/home/rtubiopa/.satnet/logs/*’: No such file or directory

It would be great if you could take a look at these issues. Try to make the installation of the protocol in a clean virtual machine and let me know what we have to do to avoid these problems.

Thanks! Ricardo.

**Comment by rtubio** [comment]
Actually, you have to erase from the installation script all the shortcuts and GUI dependencies; the protocol has to run through supervisor with no GUI...

**Comment by rtubio** [comment]
I have just tried to install the protocol and I have found the following issue:

    rtubiopa@satnet:~/protocol$ sudo /etc/init.d/satnetprotocol start
    [sudo] password for rtubiopa: 
    Starting SatNet protocol...
    Unhandled Error
    Traceback (most recent call last):
      File "/home/rtubiopa/protocol/.venv/local/lib/python2.7/site-packages/twisted/application/app.py", line 657, in run
        runApp(config)
      File "/home/rtubiopa/protocol/.venv/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 23, in runApp
        _SomeApplicationRunner(config).run()
      File "/home/rtubiopa/protocol/.venv/local/lib/python2.7/site-packages/twisted/application/app.py", line 389, in run
        self.application = self.createOrGetApplication()
      File "/home/rtubiopa/protocol/.venv/local/lib/python2.7/site-packages/twisted/application/app.py", line 454, in createOrGetApplication
        application = getApplication(self.config, passphrase)
    --- <exception caught here> ---
      File "/home/rtubiopa/protocol/.venv/local/lib/python2.7/site-packages/twisted/application/app.py", line 465, in getApplication
        application = service.loadApplication(filename, style, passphrase)
      File "/home/rtubiopa/protocol/.venv/local/lib/python2.7/site-packages/twisted/application/service.py", line 403, in loadApplication
        application = sob.loadValueFromFile(filename, 'application', passphrase)
      File "/home/rtubiopa/protocol/.venv/local/lib/python2.7/site-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
        exec fileObj in d, d
      File "/home/rtubiopa/protocol/server_amp_daemon.tac", line 3, in <module>
        from ampauth.server import CredAMPServerFactory
    exceptions.SyntaxError: invalid syntax (server.py, line 322)

    Failed to load application: invalid syntax (server.py, line 322)

Am I doing anything wrong? I just executed the installation script as expected (I think)... thanks!

**Comment by rtubio** [comment]
With the last  commit, it starts up! Great!
